AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  StoritmpBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: storitmp

  ThumbnailGeneratorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: thumbnail_generator/
      Handler: app.lambda_handler
      Runtime: python3.9
      # Policies:
      #   - S3ReadPolicy
      Architectures:
        - x86_64
      Events:
        ThumbnailGenerator:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
        MyS3Event:
          Type: S3
          Properties:
            Bucket: !Ref StoritmpBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: inputs/
                  - Name: suffix
                    Value: .jpg

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ThumbnailGeneratorApi:
    Description: API Gateway endpoint URL for Prod stage for Thumbnail Generator function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ThumbnailGeneratorFunction:
    Description: Thumbnail Generator Lambda Function ARN
    Value: !GetAtt ThumbnailGeneratorFunction.Arn
  ThumbnailGeneratorFunctionIamRole:
    Description: Implicit IAM Role created for Thumbnail Generator function
    Value: !GetAtt ThumbnailGeneratorFunctionRole.Arn 
